
import Head from "next/head";
import Hero from "../components/Hero";
import Features from "../components/Features";
import Pricing from "../components/Pricing";
import styles from "../styles/Home.module.css";
import Testimonial from "../components/Testimonial";
import Footer from "../components/Footer";
import Sidebar from "../components/Sidebar";
import Backdrop from "../components/Backdrop";

export default function Home({open , setopen}) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Get startup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar open={open} setopen={setopen} />
      <Backdrop open={open} setopen={setopen}/>
      <div id="home" className={styles.hero}>
        <Hero />
      </div>
      <div id="features">
        <Features />
      </div>
      <div id="pricing">
        <Pricing />
      </div>
      <div id="testimonial">
        <Testimonial />
      </div>
      <Footer />
    </div>
  );
}
