import Head from 'next/head';
import Hero from '../components/Hero';
import Features from '../components/Features';
import Pricing from '../components/Pricing';
import styles from '../styles/Home.module.css';


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Get startup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id="home" className={styles.hero}>
         <Hero />
      </div> 
      <div id="features">
         <Features />
      </div>
      <div id="pricing">
         <Pricing />
      </div>
    </div>
  )
}
